learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    
    
    
]

learning_logs/urls.py
from django.conf.urls import url
from . import views

""" Define padraões de URL para learning_logs"""

app_name =  'learning_logs'

urlpatterns = [
	# Página inicial
	url(r'^$', views.index, name='index'),
	
	#Motra todos os assuntos
	url(r'^topics/$', views.topics, name='topics'),
	
	# Página de detalhes para um único assunto
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	
	# Página para adicionar um novo assunto
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	
	# Página para adicionar uma nova entrada. 
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	
	# Página para editar uma entrada
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
	
	
	
	
	
]

users/urls.py
""" Define padrões de URL para users. """
from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

app_name =  'users'
urlpatterns= [
	# Pagina de login
	url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
	

]

learning_logs/models.py
from django.db import models

class Topic(models.Model):
	""" Um assunto sobre o qual o usuário esta aprendendo. """
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		""" Devolve uma representação em string do modelo."""
		return self.text
		
class Entry(models.Model):
	""" Algo especifico aprendido sobre um assunto"""
	# essa chave associa cada entrada a um assunto.
	topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	
class Meta:
	verbose_name_plural = 'entries'
	
	def __str__(self):
		""" Devolve uma representação em string do modelo"""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields =['text']
		labels={'text': ''}


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
	""" A pagina inicial de learning LOG. """
	return render(request, 'learning_logs/index.html')
							
def topics(request):
	""" Mostra todos os assunto """
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}	
	return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
	"""	 Mostra um único assunto e todas as suas entradas. """	
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context ={'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
	""" Adiciona um novo assunto. """
	if request.method != 'POST':
		# Nenhum dado submetido; cria um formulário em branco
		form = TopicForm()
	else:
		# Dados de POST submetidos; cria um formulário em branco	
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
			
	context = {'form':form}		
	return render(request, 'learning_logs/new_topic.html', context)	
		
def new_entry(request, topic_id):	
	""" Acrescenta uma nova entrada para um assunto em particular. """		
	topic = Topic.objects.get(id=topic_id)
	
	if request.method != 'POST':
		# Nenhum dado submetido; cria um formulário em branco
		form = EntryForm()
	else:
		# Dados de POST submetidos; processa os dados
		form = EntryForm(data=request.POST)	
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
	
	context = {'topic': topic, 'form': form}		
	return render(request, 'learning_logs/new_entry.html', context)
	
def edit_entry(request, entry_id):
	""" Edita uma entrada existente."""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if request.method != 'POST':
		# Requisiçao inicial, preenche previamente o formulário com a entrada atual
		form = EntryForm(instance=entry)
	else:			
		# Dados de POST submetidos;processo os dados
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
	context = {'entry': entry, 'topic': topic, 'form': form}		
	return render(request, 'learning_logs/edit_entry.html', context)
				
	
	
	
	

	
	
	
	
	

users/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Registro de apreendizagem</a> - 
	<a href="{% url 'learning_logs:topics'%}">Tópicos</a> -
	{% if user.is_authenticated %}
		ola, {{ user.name }}.
		{% else %}
			<a href="{% url 'users:login' %}">Logar </a>
	{% endif %}		
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Editar entrada</p>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Salvar alterações</button>
	
	
	</form>



{% endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}


<p>Registro de aprendizado ajuda a acompanhar o seu aprendizado, 
para qualquer tópico sobre o qual você esteja aprendendo.</p>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
<P><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </P>

<p>Nova Entrada:</p>

	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Nova entrada </button>	
	</form>
	
{% endblock content %}	
	

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p> Novo Tópico:</p>
	<form action="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Novo Tópico</button>
	</form>
{% endblock content %}
	

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<p> Tópicos: {{ topic }}</p>
	<p><h3>Entradas:</h3></p>
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">Adicionar entrada </a>
	</p>
	
	<p>Entradas: </p>
		<Ul>
			{% for entry in entries %}			
			<li>
				<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
				<p>{{ entry.text|linebreaks}}</p>
				<p>
					<a href="{% url 'learning_logs:edit_entry' entry.id %}">Editar entrada</a>
				</p>
			
			</li>
			{% empty %}
			<li>
				Ainda não há entradas inseridas.
			
			</li>
			{% endfor %}		
		
		 </Ul>
{% endblock content %}		 

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p> Tópicos </p>
	<ul>
		{% for topic in topics %}
			<li>				
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>		
						
			</li>
		{% empty %}	
		<li> Não há tópicos inseridos ainda.</li>
		{% endfor %}	
	</ul>
	<a href="{% url 'learning_logs:new_topic' %}">Novo tópico</a>

{% endblock content %}

users/templates/login.html
{% extends "learnig_logs/base.html"%}

{% block content %}

	{% if form.erros %}
	<p>Seu nome de usuário e senha não coincidem. Por favor, tente novamente.</p>
	{% endif %}
	<form method="post" action="{%  url 'users:login' %}">
		{% endif %}
		{{ form.as_p }}
		<button type="hidden" name="next" value="{% url 'learning_logs:index' %}"></button>
	
	</form>


{% endblock content %}